### ISSUE TITLE
Seznámení s Githubem a vize projektu 

### ISSUE THREAD

**Issue by HammerH0ld** [HammerH0ld/TATECON-s.r.o#3]
- [x] vysvětlení principů Issues - jak fungují, co jsou to tagy, komunikace skrz ně, komentáře
- [x] vysvětlení pull requests a commitů - pro ty co, již znají, tak jen osvěžení znalostí či vyjasnění nesrovnalostí
- [x] prvotní seznámení a ucelení vize projektu - krátké shrnutí toho jaká je vize projektu a postup jeho implementace (prostor pro nápady, postřehy či bonusy)

**Comment by MLorenz04** [comment]
@HammerH0ld tobě nechám poslední část
